---
jupyter:
  kernelspec:
    display_name: R
    language: R
    name: ir
---

```{r}
if (!require("pacman")) install.packages("pacman")
pacman::p_load(tidyverse, ggplot2, dplyr, lubridate, stringr, readxl, data.table, gdata, scales, kableExtra)
```

```{r}
plan.data <- read_csv("data/output/plan_data.csv")
service.data <- read_csv("data/output/service_area.csv")
plan.type.year1 <- plan.data %>% group_by(plan_type) %>% count() %>% arrange(-n) %>% filter(plan_type!="NA")
plan.type.year2 <- plan.data %>% 
  filter(snp == "No" & eghp == "No" & (planid < 800 | planid >= 900)) %>% 
  group_by(plan_type) %>% count() %>% arrange(-n)

plan.type.enroll <- plan.data %>%
  inner_join(service.data %>% 
               select(contractid, fips, year), 
             by=c("contractid", "fips", "year")) %>%
  filter(snp == "No" & eghp == "No" & (planid < 800 | planid >= 900)) %>% 
  group_by(plan_type) %>% summarize(n=n(), enollment=mean(avg_enrollment, na.rm=TRUE)) %>% arrange(-n)
```

```{r}
options(knitr.kable.NA = 0)
knitr::kable(plan.type.year1, 
             col.names=c("Plan Type","Count"),
             format.args=list(big.mark=","), booktabs = TRU)
```

```{r}
options(knitr.kable.NA = 0)
knitr::kable(plan.type.year2, 
             col.names=c("Plan Type","Count"),
             format.args=list(big.mark=","), booktabs = TRUE)
```

```{r}
options(knitr.kable.NA = 0)
knitr::kable(plan.type.enroll, digits=0,
             col.names=c("Plan Type","Count","Avg Enrollments"),
             format.args=list(big.mark=","), booktabs = TRUE)
```


